# Generated by Django 2.1 on 2019-12-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='tag',
        ),
    ]
