# Generated by Django 2.1 on 2019-12-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_imagenes_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias', verbose_name='Etiqueta'),
        ),
    ]
