# Generated by Django 2.1 on 2019-12-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_imagenes_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorio',
            name='tag',
        ),
    ]
