# Generated by Django 2.1 on 2019-12-12 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_remove_repositorio_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='tag',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias', verbose_name='Etiqueta'),
            preserve_default=False,
        ),
    ]
