# Generated by Django 2.1 on 2019-12-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_repositorio_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='tag1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias', verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='tag1',
            field=models.ForeignKey(default=-1.1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias', verbose_name='Etiqueta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='Categoría'),
        ),
    ]
