# Generated by Django 2.1 on 2019-12-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20191212_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='tag1',
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias', verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias', verbose_name='Etiqueta'),
        ),
    ]
