# Generated by Django 2.1 on 2019-12-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20191212_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='tag',
            field=models.ForeignKey(default=-1.2, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Categorias', verbose_name='Etiqueta'),
            preserve_default=False,
        ),
    ]
